create table if not exists product_line(
        id BIGINT primary key NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
        name varchar,
        active BOOLEAN
);