CREATE TABLE IF NOT EXISTS products (
    product_id BIGINT PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name VARCHAR(255) NOT NULL,
    price NUMERIC(10,2) NOT NULL,
    cost NUMERIC(10,2) NOT NULL,
    unit VARCHAR(255) NOT NULL,
    brand VARCHAR(255),
    category_id BIGINT,
    ncm VARCHAR,
    line_id BIGINT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    active BOOLEAN,
    FOREIGN KEY (category_id) REFERENCES product_category (id),
    FOREIGN KEY (line_id) REFERENCES product_line (id)
);
