CREATE TABLE IF NOT EXISTS stock (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    product_id BIGINT REFERENCES products (product_id),
    price DOUBLE PRECISION,
    cost DOUBLE PRECISION,
    quantity INT,
    entries INT,
    exits INT,
    added_at DATE,
    updated_at DATE,
    CONSTRAINT stock_pkey PRIMARY KEY (id)
);
