CREATE TABLE IF NOT EXISTS purchases (
    id BIGINT NOT NULL NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    supplier_id BIGINT,
    total NUMERIC(10,2),
    paid_amount NUMERIC(10,2),
    balance NUMERIC(10,2),
    active BOOLEAN DEFAULT TRUE,
    entry_at TIMESTAMP,
    created_at TIMESTAMP,
    finished_At TIMESTAMP,
    canceled_at TIMESTAMP,
    description VARCHAR(255),
    payment_method VARCHAR(50),
    payment_status VARCHAR(50),
    nfe VARCHAR(11),
    CONSTRAINT purchases_pkey PRIMARY KEY (id),
    CONSTRAINT fk_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers(id)
);