@startuml
skin rose
title Diagrama de Sequência - Produto (MVC)

actor Usuario

participant TelaListagemProduto <<view>>
participant ProdutoController <<controller>>
participant RepositorioProduto <<repository>>
participant Produto <<model>>

== Listar Produtos ==
Usuario -> TelaListagemProduto: "Solicita listagem de produtos"
TelaListagemProduto -> ProdutoController: "listarProdutos()"
ProdutoController -> RepositorioProduto: "findAll()"
RepositorioProduto --> ProdutoController: "Retorna lista de produtos"
ProdutoController --> TelaListagemProduto: "Envia lista de produtos"
TelaListagemProduto -> Usuario: "Exibe lista de produtos"

== Cadastrar Produto ==
Usuario -> TelaFormularioCadastroProduto: "Solicita cadastro de produto"
TelaFormularioCadastroProduto -> TelaFormularioCadastroProduto: "Exibir formulário"
Usuario -> TelaFormularioCadastroProduto: "Envia dados do produto"
TelaFormularioCadastroProduto -> ProdutoController: "cadastrarProduto(produto)"
ProdutoController -> Produto: "Criar instância do produto"
ProdutoController -> RepositorioProduto: "save(produto)"
RepositorioProduto --> ProdutoController: "Confirmação de salvamento"
ProdutoController --> TelaFormularioCadastroProduto: "Retorna status do cadastro"
TelaFormularioCadastroProduto -> Usuario: "Exibe confirmação"

== Atualizar Produto ==
Usuario -> TelaFormularioAtualizacaoProduto: "Solicita atualização de produto"
TelaFormularioAtualizacaoProduto -> ProdutoController: "buscarProdutoPorId(id)"
ProdutoController -> RepositorioProduto: "findById(id)"
RepositorioProduto --> ProdutoController: "Retorna produto"
ProdutoController --> TelaFormularioAtualizacaoProduto: "Envia produto para atualização"
Usuario -> TelaFormularioAtualizacaoProduto: "Envia dados atualizados"
TelaFormularioAtualizacaoProduto -> ProdutoController: "atualizarProduto(produto)"
ProdutoController -> Produto: "Atualiza atributos"
ProdutoController -> RepositorioProduto: "save(produto)"
RepositorioProduto --> ProdutoController: "Confirmação de salvamento"
ProdutoController --> TelaFormularioAtualizacaoProduto: "Retorna status da atualização"
TelaFormularioAtualizacaoProduto -> Usuario: "Exibe confirmação"

== Deletar Produto ==
Usuario -> TelaConfirmacaoDelecaoProduto: "Solicita deleção de produto"
TelaConfirmacaoDelecaoProduto -> TelaConfirmacaoDelecaoProduto: "Exibe mensagem de confirmação"
Usuario -> TelaConfirmacaoDelecaoProduto: "Confirma deleção"
TelaConfirmacaoDelecaoProduto -> ProdutoController: "deletarProduto(id)"
ProdutoController -> RepositorioProduto: "delete(id)"
RepositorioProduto --> ProdutoController: "Confirmação de exclusão"
ProdutoController --> TelaConfirmacaoDelecaoProduto: "Retorna status da exclusão"
TelaConfirmacaoDelecaoProduto -> Usuario: "Exibe confirmação"

@enduml
