@startuml
skin rose
title Diagrama de Sequência - Obter Produtos Mais Vendidos

actor Usuário as usr
participant MetricasView as view
participant MetricasController as ctrl
participant MetricasService as svc
participant PedidoRepository as repo
participant Produto as model

usr -> view : Solicitar produtos mais vendidos
view -> ctrl : obterProdutosMaisVendidos(startDate, endDate)
ctrl -> svc : obterProdutosMaisVendidos(startDate, endDate)
svc -> repo : findByDataBetween(startDate, endDate)
repo --> svc : Retorna lista de pedidos
svc -> model : Processar dados para encontrar produtos mais vendidos
model --> svc : Retorna lista de produtos mais vendidos
svc --> ctrl : Retorna lista de produtos
ctrl --> view : Envia dados para exibição
view -> usr : Exibir lista de produtos mais vendidos

@enduml
