@startuml
skin rose

title Diagrama de Sequência - Criar Pedido

actor Cliente as cli
participant "Sistema" as sis
participant Pedido as ped
participant ProdutoPedido as pp
participant Produto as prod
participant Entregador as ent
participant FormaPagamento as fp
participant Caixa as caixa

cli -> sis : Solicitar criação de pedido
sis -> prod : Consultar disponibilidade de produtos
prod --> sis : Retorna produtos disponíveis

sis -> pp : Adicionar produtos ao pedido
pp --> sis : Confirma produtos adicionados

sis -> ent : Selecionar entregador
ent --> sis : Retorna entregador selecionado

sis -> fp : Selecionar forma de pagamento
fp --> sis : Confirma forma de pagamento

sis -> ped : Criar pedido com os dados fornecidos
ped --> sis : Pedido criado com sucesso

sis -> caixa : Atualizar saldo do caixa
caixa --> sis : Saldo atualizado

cli <-- sis : Pedido criado com sucesso!

@enduml
