@startuml
skin rose
title Diagrama de Sequência - Usuário (MVC)

actor Usuario

participant TelaLogin <<view>>
participant UsuarioController <<controller>>
participant Token <<model>>
participant UsuarioRepository <<repository>>
participant Usuario <<model>>

== Login ==
Usuario -> TelaLogin: "Solicita login"
TelaLogin -> UsuarioController: "login(email, senha)"
UsuarioController -> UsuarioRepository: "buscarPorEmail(email)"
UsuarioRepository --> UsuarioController: "Retorna usuário"
UsuarioController -> Token: "gerarToken(usuario)"
Token --> UsuarioController: "Retorna token"
UsuarioController --> TelaLogin: "Retorna token"
TelaLogin -> Usuario: "Exibe resultado do login"

== Atualizar Usuário ==
Usuario -> TelaAtualizacaoUsuario: "Solicita atualização de dados"
TelaAtualizacaoUsuario -> UsuarioController: "atualizar(telefone, role, email, senha)"
UsuarioController -> UsuarioRepository: "buscarPorEmail(email)"
UsuarioRepository --> UsuarioController: "Retorna usuário"
UsuarioController -> Usuario: "atualiza dados"
UsuarioController -> UsuarioRepository: "salvar(usuario)"
UsuarioRepository --> UsuarioController: "Confirma atualização"
UsuarioController --> TelaAtualizacaoUsuario: "Retorna status de atualização"
TelaAtualizacaoUsuario -> Usuario: "Exibe confirmação"

== Deletar Usuário ==
Usuario -> UsuarioController: "deletar(id)"
UsuarioController -> UsuarioRepository: "deletarPorId(id)"
UsuarioRepository --> UsuarioController: "Confirma deleção"
UsuarioController -> Usuario: "Deleta usuário"
Usuario -> UsuarioController: "Confirma exclusão"

== Cadastrar Usuário ==
Usuario -> UsuarioController: "cadastrar(nome, telefone, role, email, senha)"
UsuarioController -> Usuario: "Cria novo usuário"
UsuarioController -> UsuarioRepository: "salvar(usuario)"
UsuarioRepository --> UsuarioController: "Confirma cadastro"
UsuarioController -> Usuario: "Retorna status de cadastro"
Usuario -> UsuarioController: "Confirma criação"

@enduml
