@startuml Dominio
skin rose

title Diagrama de Classes - Modelo de Domínio

' Classes de Modelo
class Endereco {
  - numero: String
  - rua: String
  - bairro: String
  - cidade: String
  - estado: String
}


class Cliente {
  - nome: String
  - endereco: Endereco
  - telefone: String
  - pedidos: List<Pedido>
}

class Produto {
  - nome: String
  - unidade: String
  - precoUnitario: double
  - custo: double
  - marca: String
  - linha: String
}

class ProdutoPedido {
  - produto: Produto
  - quantidade: int
  - precoUnitario: double
  --
  + calcularValorItem(): double
}

class Pedido {
  - cliente: Cliente
  - entregador: Entregador
  - produtos: List<ProdutoPedido>
  - status: StatusPedido
  - valorRecebido: double
  - valorTotal: double
  - formaDePagamento: FormaPagamento
  - data: LocalDateTime
  --
  + calcularValorTotalPedido(): double
}

class Usuario {
  - nome: String
  - telefone: String
  - acesso: Acesso
  - email: String
  - senha: String
}

enum Acesso{
    DONO
    FUNCIONARIO
    GESTOR
}

class Token{
    - token: String
}

class Entregador {
  - nome: String
  - telefone: String
}

enum StatusPedido {
  PENDENTE
  ENTREGUE
  ATRASADO
  CANCELADO
}

enum FormaPagamento {
  PIX
  DEBITO
  CREDITO
  DINHEIRO
  BOLETO
}

class Estoque {
  - produto: Produto
  - quantidadeInicial: int
  - entradas: int
  - saidas: int
  --
  + calcularDisponivel(): int
}


class Caixa {
    - saldo: double
    - transacoes: List<Transacao>
}

class Transacao {
    - valor: double
    - status: StatusTransacao
    - tipo: TipoTransacao
    - descricao: double
    - data: LocalDateTime
}

enum TipoTransacao {
  RECEITA
  DESPESA
  ESTORNO
  TRANSFERENCIA
}

enum StatusTransacao {
  PAGA
  PENDENTE
  CANCELADA
}

class Metricas{
    - dataInicio: LocalDate
    - dataFim: LocalDate
    + getTotalVendas(): int
    + getGastoTotais(): double
    + getProdutoMaisVendidos(): List<Produtos>
    + getReceitaAcumulada(): double
}
note right of Metricas
  A classe metricas pode acessar
  outras classes e buscar dados,
  pode ser adicionado mais buscas 
  posteriormente,
  e pode fazer buscas por View no
  banco de dados
end note

Usuario "1" - "1" Token: tem
Usuario "1" -- "1" Acesso: tem

Cliente "1" -- "1..*" Pedido: possui
Cliente "1" -- "1" Endereco : possui
Pedido "1..*" -- "1" Entregador : contém
Pedido "1..*" -- "1..*" ProdutoPedido : contém
ProdutoPedido "1" -- "1" Produto : contém
Pedido "1" -- "1" StatusPedido : tem
Pedido "1" -- "1" FormaPagamento : tem
Estoque "1" -- "1" Produto : refere

Caixa "1"--"0..*" Transacao: tem
Transacao "1"-"1" TipoTransacao: tem
Transacao "1"--"1" StatusTransacao: tem
Metricas "1"--"1" Transacao: acessa
Metricas "1"--"1" Pedido: acessa

@enduml
