@startuml Pedido

skin rose

title Diagrama de Classes MVC - Pedido

package "Visão (View)" {
    class TelaCriacaoPedido <<view>> {
        + exibirFormularioCriacao(): void
        + obterDadosPedido(): Pedido
    }

    class TelaAtualizacaoStatusPedido <<view>> {
        + exibirFormularioAtualizacaoStatus(): void
        + obterNovoStatus(): StatusPedido
    }

    class TelaConsultaPedido <<view>> {
        + exibirPedido(pedido: Pedido): void
        + solicitarIdPedido(): int
    }

    class TelaCancelamentoPedido <<view>> {
        + exibirConfirmacaoCancelamento(): boolean
        + solicitarIdPedidoParaCancelar(): int
    }
}

package "Controle (Controller)" {
    class PedidoController <<controller>> {
        + criarPedido(pedido: Pedido): boolean
        + atualizarStatusPedido(id: int, status: StatusPedido): boolean
        + buscarPedido(id: int): Pedido
        + cancelarPedido(id: int): boolean
    }
}

package "Modelo (Model)" {
    enum StatusPedido <<model>> {
        PENDENTE
        ENTREGUE
        ATRASADO
        CANCELADO
    }

    enum FormaPagamento <<model>> {
        PIX
        DEBITO
        CREDITO
        DINHEIRO
        BOLETO
    }

    class Pedido <<model>> {
        - idCliente: int
        - entregador: Entregador
        - produtos: List<ProdutoPedido>
        - status: StatusPedido
        - valorRecebido: double
        - valorTotal: double
        - formaDePagamento: FormaPagamento
        - data: LocalDateTime
        --
        + calcularValorTotalPedido(): double
    }

    class Entregador <<model>> {
        - id: int
        - nome: String
        - telefone: String
    }

    class ProdutoPedido <<model>> {
        - idProduto: int
        - quantidade: int
        - precoUnitario: double
        --
        + calcularValorItem(): double
    }

    class Produto <<model>> {
        - id: int
        - nome: String
        - unidade: String
        - precoUnitario: double
        - custo: double
        - marca: String
        - linha: String
    }
}

'Telas interagem com Controller
TelaCriacaoPedido --> PedidoController: "solicita criação de pedido"
TelaAtualizacaoStatusPedido --> PedidoController: "solicita atualização de status"
TelaConsultaPedido --> PedidoController: "solicita busca de pedido"
TelaCancelamentoPedido --> PedidoController: "solicita cancelamento de pedido"

'Controller manipula Modelo
PedidoController --> Pedido: "manipula"
PedidoController --> StatusPedido: "atualiza status"
PedidoController --> FormaPagamento: "define forma de pagamento"

'Relacionamentos entre as classes
Pedido "1..*"-down-"1" Entregador: "contem"
Pedido "1"--"1..*" ProdutoPedido: "contém"
Pedido "1"--"1" StatusPedido: "tem status"
Pedido "1"--"1" FormaPagamento: "tem forma de pagamento"
ProdutoPedido "1"-"1" Produto:contem

@enduml
