spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/sysagua_db}  # Variável de ambiente para o URL do banco de dados, com valor default
    username: ${DB_USERNAME:postgres}                       # Variável de ambiente para o nome de usuário do banco, com valor default
    password: ${DB_PASSWORD:testpassword}                   # Variável de ambiente para a senha do banco, com valor default
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect  # Dialeto do PostgreSQL
    show-sql: true                                          # Exibe as consultas SQL no console
    generate-ddl: true                                      # Gera DDL automaticamente em testes
    hibernate:
      ddl-auto: update                                       # Atualiza o esquema do banco automaticamente
      format-sql: true                                       # Formata as consultas SQL para facilitar a leitura
      enable_lazy_load_no_trans: true                        # Habilita carregamento lazy fora de transações

  flyway:
    locations: classpath:db/migration/postgres               # Localização dos scripts de migração do Flyway
    baseline-on-migrate: true                                # Força o Flyway a manter o controle de versões no banco
    enabled: true                                            # Habilitar o Flyway para gerenciar migrações

default-user:
  password: senha123
  email: usuario@gmail.com

security:
  config:
    key: ${JWT_SECRET_KEY:your-secret-key}                   # Variável de ambiente para a chave JWT (pode ser definida no ambiente)
    expiration: ${JWT_EXPIRATION:12}                         # Definir o tempo de expiração do JWT (hora)
